### ISSUE TITLE
tests/killed-info times out

### ISSUE THREAD

**Issue by 2072** [krakjoe/pthreads#273]
```
PHP         : /opt/php-5.5.9/bin/php
PHP_SAPI    : cli
PHP_VERSION : 5.5.9
ZEND_VERSION: 2.5.0
PHP_OS      : Linux - Linux vps44763 2.6.32-042stab084.14 #1 SMP Mon Dec 16 18:16:56 MSK 2013 x86_64
INI actual  : /home/john/src/pthreads/tmp-php.ini
More .INIs  :
CWD         : /home/john/src/pthreads
Extra dirs  :
VALGRIND    : Not used
```

```
---- EXPECTED OUTPUT
bool(true)
array(4) {
  ["scope"]=>
  string(10) "TestThread"
  ["function"]=>
  string(3) "run"
  ["file"]=>
  string(%d) "%s"
  ["line"]=>
  int(%d)
}
---- ACTUAL OUTPUT
** ERROR: process timed out **
---- FAILED
```

**Comment by 2072** [comment]
With my new gdb skills I was able to get a phpSide backtrace when the process is left hanging:

```
(gdb) set_ts 0x146add0
(gdb) ____executor_globals
(gdb) dump_bt $eg.current_execute_data
[0x2ac7d47d6328] Thread->join() /home/john/src/pthreads/tests/killed-info.php:13
```
So this is the `join()` called right after the `kill()`.

I've very recently upgraded my 1vCore vps to 3vCore one and I still get this problem but sometimes it passes though. So it might be related to the way the scheduler works in OpenVZ containers...

**Comment by 2072** [comment]
Since I'm able to reproduce the issue easily I decided to find out what's going on:

I made the following changes to make Pthreads display some debug info: https://github.com/2072/pthreads/commit/4df66eab3a54bb3dd7ad311341219496480f61d7

Then I executed the following test script:
```php
<?php
error_reporting(E_ALL | E_STRICT);
ini_set("display_startup_errors", true);

class TestThread extends Thread
{
    public function run()
    {
        sleep(5);
    }
}

$t = new TestThread();
$t->start();
$t->kill();
$t->join();

var_dump($t->isTerminated());
var_dump($t->getTerminationInfo());
```

and obtained the following output:

```
1F3CBF0 is in pthreads_state_set() PHP line: 0
Joining from 1BFEB20... from php line 16
1F3CBF0 is in pthreads_state_set() PHP line: 0

 HEY!! I (1F3CBF0) am already in there!: 6

I (1F3CBF0) was murdered while changing state: 6! (on kill pthreads_state_set() returned: 1)
we were killed while in 'pthread_cond_broadcast()' a dead lock is on the move. Sleeping for 120s
```

While it slept I attach gdb and got the following backtrace on thread #2 (1F3CBF0):

```
#0  0x00007f18b312e2bd in nanosleep () at ../sysdeps/unix/syscall-template.S:82
#1  0x00007f18b312e130 in __sleep (seconds=<optimized out>, seconds@entry=120) at ../sysdeps/unix/sysv/linux/sleep.c:138
#2  0x00007f18b18942e0 in pthreads_kill_handler (signo=10) at /home/john/src/pthreads/src/object.c:838
#3  <signal handler called>
#4  pthread_cond_broadcast@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_broadcast.S:98
#5  0x00007f18b188f4f7 in pthreads_synchro_notify (sync=<optimized out>, tsrm_ls=tsrm_ls@entry=0x1687bf0) at /home/john/src/pthreads/src/synchro.c:96
#6  0x00007f18b188f9e5 in pthreads_state_set (state=0x1686cf0, mask=mask@entry=2, tsrm_ls=0x1687bf0, tsrm_ls@entry=0x84) at /home/john/src/pthreads/src/state.c:108
#7  0x00007f18b1894dda in pthreads_routine (arg=0x1686360) at /home/john/src/pthreads/src/object.c:980
#8  0x00007f18b3414b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#9  0x00007f18b315e7bd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#10 0x0000000000000000 in ?? ()
```

So the problem is obvious now, we can fix this either by fixing the test so that it waits for the thread to be started before killing it or the kill handler must be made more clever but since killing threads is not a recommended practice anyway, fixing the test is probably enough...
