### ISSUE TITLE
Stackable array code fails to run properly

### ISSUE THREAD

**Issue by emilxp** [krakjoe/pthreads#469]
I've been struggling with this for some time now. I have a worker and a stackable that I want to stack on the worker. I want to push that stackable to an array of stackables. That array is a member of the worker(not a static member). The point is to maintain the reference to the stackable so that it won't get destroyed. I do it this way for convenience, but it won't work. I read that normal php arrays aren't thread safe and I must use something like this:
```php
class SafeArray extends Stackable {
    public function run() {
        echo "array created\n";
    }
}
```
Stackable implements array access, countable and traversable so it could be used as a thread safe array, if I understand correctly. I think it could work with Threaded too. However it doesn't work for me. Here's my code:

```php
<?php
class SafeArray extends Stackable {
    public function run() {
        echo "array created\n";
    }
}

class Task extends Stackable {
    public function run() {
        echo "executing task\n";
    }
}

class Executor extends Worker {
    public $array;
    public function __construct() {
        $this->array = new SafeArray(); /* the php engine claims that this array
was destroyed and what does it mean by connect? */
        var_dump($this->array);
    }

    public function run() {
        echo "here";
        var_dump($this->array);
        echo "here";
    }
}

$executor = new Executor;
$task = new Task();
$executor->stack($task);
$executor->start();
$executor->shutdown();
```

Here's what the console says:
```Batchfile
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'pthreads d
etected an attempt to connect to a SafeArray which has already been destroyed' i
n D:\maxbot\test.php:18
Stack trace:
#0 D:\maxbot\test.php(18): Executor::__construct()
#1 D:\maxbot\test.php(28): Executor->__construct()
#2 {main}
  thrown in D:\maxbot\test.php on line 18

Fatal error: Uncaught exception 'RuntimeException' with message 'pthreads detect
ed an attempt to connect to a SafeArray which has already been destroyed' in D:\
maxbot\test.php:18
Stack trace:
#0 D:\maxbot\test.php(18): Executor::__construct()
#1 D:\maxbot\test.php(28): Executor->__construct()
#2 {main}
  thrown in D:\maxbot\test.php on line 18
```
Here's my phpinfo(it was too big so I piped the output of php -info to a file and pasted it's contents in pastebin.com): http://pastebin.com/kyjFJS5V

pthreads version: 2.0.10

**Comment by cottton** [comment]
Yepp, had the same "problem" once.
Cant really remember what this causes. Was about the __construct.
This works:
```php
class SafeArray extends Stackable {
    public function run() {
        echo "array created\n";
    }
}

class Task extends Stackable {
    public function run() {
        echo "executing task\n";
    }
}

class Executor extends Worker {
    public $array;
    public function __construct(SafeArray $SafeArray) {
        $this->array = $SafeArray;
        var_dump($this->array);
    }

    public function run() {
        echo "here";
        var_dump($this->array);
        echo "here";
    }
}

$SafeArray = new SafeArray();
$executor = new Executor($SafeArray);
$task = new Task();
$executor->stack($task);
$executor->start();
$executor->shutdown();
```

**Comment by krakjoe** [comment]
You need to retain the reference outside of the threaded object.

The example above is correct.

**Comment by emilxp** [comment]
Thank you so much cottton and Joe! :)
