### ISSUE TITLE
getting wrong class name using get_class(self::Object) from outside

### ISSUE THREAD

**Issue by cottton** [krakjoe/pthreads#474]
As the title says ^
I first wondered if this is right ... but its not.
(i found 2 posts about this problem - but there where to compelx, also old - so i thought i better open a new one)

short:
using `get_class(self::$MyClassStoreStatic)` from inside works as expected.
using `get_class(self::$MyClassStoreStatic)` from outside returns wrong class name.

See example: (i really tried to keep it as simple as f* as possible :)
```php
<?php
function debug($method, $called_class, $MyClassStoreStatic, $MyClass){
    echo $method . PHP_EOL .
        "get_called_class():\t\t\t" . $called_class . PHP_EOL .
        "get_class(self::\$MyClassStoreStatic)\t" . $MyClassStoreStatic . PHP_EOL .
        "get_class(\$this->MyClass)\t\t" . $MyClass . PHP_EOL .
        str_repeat('-', 50) . PHP_EOL;
}
class MyClass {}
class MyClassStoreStatic {}
class Main extends Thread
{
    protected static $MyClassStoreStatic;
    protected $MyClass;
    final public function run()
    {
        self::$MyClassStoreStatic = new MyClassStoreStatic();
        $this->MyClass = new MyClass();
        echo PHP_EOL . "INSIDE" . PHP_EOL . PHP_EOL;
        $this->method_A();
    }
    final public function method_A()
    {
        debug(
            __METHOD__,
            get_called_class(),
            get_class(self::$MyClassStoreStatic),
            get_class($this->MyClass)
        );
        $this->method_B();
        $this->method_C();
    }
    final protected function method_B()
    {
        debug(
            __METHOD__,
            get_called_class(),
            get_class(self::$MyClassStoreStatic),
            get_class($this->MyClass)
        );
    }
    final private function method_C()
    {
        debug(
            __METHOD__,
            get_called_class(),
            get_class(self::$MyClassStoreStatic),
            get_class($this->MyClass)
        );
    }
}

$s = new Main();
$s->start();
sleep(1);
echo PHP_EOL . "OUTSIDE" . PHP_EOL . PHP_EOL;
$s->method_A();

/*
    windows
    PHP_VERSION 5.6.11
    php_pthreads-2.0.10-5.6-ts-vc11-x86.zip @ http://windows.php.net/downloads/pecl/releases/pthreads/2.0.10/

out:

INSIDE

Main::method_A
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    MyClassStoreStatic
get_class($this->MyClass)               MyClass
--------------------------------------------------
Main::method_B
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    MyClassStoreStatic
get_class($this->MyClass)               MyClass
--------------------------------------------------
Main::method_C
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    MyClassStoreStatic
get_class($this->MyClass)               MyClass
--------------------------------------------------

OUTSIDE

Main::method_A
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    Main        <---------- ?ERROR
get_class($this->MyClass)               MyClass
--------------------------------------------------
Main::method_B
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    Main        <---------- ?ERROR
get_class($this->MyClass)               MyClass
--------------------------------------------------

Fatal error: Uncaught exception 'RuntimeException' with message 
'pthreads detected an attempt to call private method Main::method_C from outside the threading context' 
in C:\xampp\htdocs\test.php:31
Stack trace:
#0 C:\xampp\htdocs\test.php(31): Main->method_C()
#1 C:\xampp\htdocs\test.php(57): Main->method_A()
#2 {main}
  thrown in C:\xampp\htdocs\test.php on line 31
*/


/*
    linux using
    PHP_VERSION 5.6.10-1~dotdeb+zts+7.3

out:

INSIDE

Main::method_A
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    MyClassStoreStatic
get_class($this->MyClass)               MyClass
--------------------------------------------------
Main::method_B
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    MyClassStoreStatic
get_class($this->MyClass)               MyClass
--------------------------------------------------
Main::method_C
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    MyClassStoreStatic
get_class($this->MyClass)               MyClass
--------------------------------------------------

OUTSIDE

Main::method_A
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    Main        <---------- ?ERROR
get_class($this->MyClass)               MyClass
--------------------------------------------------
Main::method_B
get_called_class():                     Main
get_class(self::$MyClassStoreStatic)    Main        <---------- ?ERROR
get_class($this->MyClass)               MyClass
--------------------------------------------------
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 
'pthreads detected an attempt to call private method Main::method_C from outside the threading context' 
in /var/www/cron/rcon/test.php:31
Stack trace:
#0 /var/www/cron/rcon/test.php(31): Main->method_C()
#1 /var/www/cron/rcon/test.php(57): Main->method_A()
#2 {main}
  thrown in /var/www/cron/rcon/test.php on line 31
*/
```

**Comment by krakjoe** [comment]
There are bugs in your logic ;)

	<?php
	function debug($method, $called_class, $MyClassStoreStatic, $MyClass){
	    echo $method . PHP_EOL .
		"get_called_class():\t\t\t" . $called_class . PHP_EOL .
		"get_class(self::\$MyClassStoreStatic)\t" . $MyClassStoreStatic . PHP_EOL .
		"get_class(\$this->MyClass)\t\t" . $MyClass . PHP_EOL .
		str_repeat('-', 50) . PHP_EOL;
	}
	class MyClass {}
	class MyClassStoreStatic {}
	class Main extends Thread
	{
	    protected static $MyClassStoreStatic;
	    protected $MyClass;
	    final public function run()
	    {
		self::$MyClassStoreStatic = new MyClassStoreStatic();
		$this->MyClass = new MyClass();
		echo PHP_EOL . "INSIDE" . PHP_EOL . PHP_EOL;
		$this->method_A();
	    }
	    final public function method_A()
	    {
		debug(
		    __METHOD__,
		    get_called_class(),
		    is_object(self::$MyClassStoreStatic) ? get_class(self::$MyClassStoreStatic) : "non-object",
		    is_object($this->MyClass) ? get_class($this->MyClass) : "non-object"
		);
		$this->method_B();
		$this->method_C();
	    }
	    final protected function method_B()
	    {
		debug(
		    __METHOD__,
		    get_called_class(),
		   is_object(self::$MyClassStoreStatic) ? get_class(self::$MyClassStoreStatic) : "non-object",
		   is_object($this->MyClass) ? get_class($this->MyClass) : "non-object"
		);
	    }
	    final private function method_C()
	    {
		debug(
		    __METHOD__,
		    get_called_class(),
		    is_object(self::$MyClassStoreStatic) ? get_class(self::$MyClassStoreStatic) : "non-object",
		    is_object($this->MyClass) ? get_class($this->MyClass) : "non-object"
		);
	    }
	}

	$s = new Main();
	$s->start();
	sleep(1);
	echo PHP_EOL . "OUTSIDE" . PHP_EOL . PHP_EOL;
	$s->method_A();

**Comment by cottton** [comment]
Oh sh**, `string get_class ([ object $object = NULL ] )`
... its a trap! :D 
Thanks man =)
