### ISSUE TITLE
Question about context binding/release of threaded objects

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#516]
Hi @krakjoe, first an example

```php
<?php
    
    $objGlobalShare = new Threaded();
    $objInstance    = new Threaded();

    class TestOne extends Thread
    {
        private $objGlobalShare;
        private $objInstance;

        public function __construct(Threaded $globalShare, Threaded $instance)
        {
            // ok
            $this->objGlobalShare   = $globalShare;
            $this->objInstance      = $instance;
        }

        public function run()
        {
            // this line binds objGlobalShare to the thread context
            $this->objGlobalShare['anykey'] = $this->objInstance;

            // binds objGlobalShare too
//            $this->objGlobalShare['anykey'] = new Threaded();
        }
    }

    $objTestOne = new TestOne($objGlobalShare, $objInstance);
    $objTestOne->start();
    $objTestOne->join();

    $objWaitMutex = new Threaded();
    $objWaitMutex->synchronized(function() use ($objWaitMutex, $objGlobalShare, $objInstance)
    {
        while(true)
        {
            // objGlobalShare gets deleted at thread join
            var_dump($objGlobalShare);

            $objWaitMutex->wait(100000);
        }
    });
```
results

Win 7 x64 php RC 5 pthreads 3.0.8

```
D:\sandbox\v3_tests>php test5.php
object(Threaded)#1 (0) {
}

Fatal error: Uncaught RuntimeException: pthreads detected an attempt to connect to an object which has already been destroyed in D:\sandbox\v3_tests\test5.php:38
Stack trace:
#0 D:\sandbox\v3_tests\test5.php(38): var_dump(Object(Threaded))
#1 [internal function]: {closure}()
#2 D:\sandbox\v3_tests\test5.php(42): Threaded->synchronized(Object(Closure))
#3 {main}
  thrown in D:\sandbox\v3_tests\test5.php on line 38
```

```
vagrant@php7dev:/var/php/libraries/liquid/test$ php test.php
object(Threaded)#1 (0) {
}
```

Debian Jessie php 7.0 latest, pthreads 3.0.9

```
Fatal error: Uncaught RuntimeException: pthreads detected an attempt to connect to an object which has already been destroyed in /var/php/libraries/liquid/test/test.php:38
Stack trace:
#0 /var/php/libraries/liquid/test/test.php(38): var_dump(Object(Threaded))
#1 [internal function]: {closure}()
#2 /var/php/libraries/liquid/test/test.php(42): Threaded->synchronized(Object(Closure))
#3 {main}
  thrown in /var/php/libraries/liquid/test/test.php on line 38
*** Error in `php': corrupted double-linked list: 0x00000000030c2820 ***
Aborted
```

My intention is to share objects across threads. I would like to use Threaded and avoid Volatile 'cause Volatile seems to be evil ;-) 

Ok, as soon as ThreadOne joins, $objGlobalShare gets deleted. But only if an element was assigned in ThreadOne::run. I would expect that an Threaded object, which was created in main context, survives a thread death. Is that possible? Maybe I'm just totally wrong with my thoughts ...

thx Joe

**Comment by krakjoe** [comment]
The Threaded object created in the main context does survive the death of the Thread.

What you assign in Thread::run is not the same object, it's a mirror (connection) object which allows the child thread to access the object created in the main context. This mirror object does get destroyed.

This is a kind of strange side effect, I admit, but there's nothing I can really do about it ...
