### ISSUE TITLE
In thread when use main thread of static variable that store resource occur segmentation fault

### ISSUE THREAD

**Issue by chopins** [krakjoe/pthreads#532]
My PHP Interpreter is 7, run below code is pseudocode, run  it after a moment is fault.  
when remove static variable, the script run correct.  
Of couse, i know used class Pool store the link. but i think is bug

```php
function db()
{
    static $link;
     if ($link instanceof mysqli && $link->ping()) {
        return $link;
    }
    //When remove above code and no error 

     $link = new mysqli('127.0.0.1', 'root', null, 'book');
    return $link;
}
class myThread extends Thread {
     public function run() {
       db()->query('SHOW PROCESSLIST');
   }
}
for($i=0;i<10000;$i++) {
(new myThread)->start()
(new myThread)->start()
(new myThread)->start()
(new myThread)->start()
}
``` 

below is gdb backtrace
```
#0  0x00000000007cee8e in _emalloc (size=56) at /home/chopin/NetBeansProjects/php-src/Zend/zend_alloc.c:2434
#1  0x00000000007cf1cd in _safe_emalloc (nmemb=<optimized out>, size=<optimized out>, offset=<optimized out>)
    at /home/chopin/NetBeansProjects/php-src/Zend/zend_alloc.c:2510
#2  0x00000000007cf241 in _ecalloc (nmemb=nmemb@entry=1, size=size@entry=56) at /home/chopin/NetBeansProjects/php-src/Zend/zend_alloc.c:2533
#3  0x000000000076892c in _mysqlnd_pecalloc (nmemb=1, size=48, persistent=<optimized out>)
    at /home/chopin/NetBeansProjects/php-src/ext/mysqlnd/mysqlnd_alloc.c:220
#4  0x000000000076a9cd in php_mysqlnd_protocol_get_command_packet_pub (protocol=<optimized out>, persistent=<optimized out>)
    at /home/chopin/NetBeansProjects/php-src/ext/mysqlnd/mysqlnd_wireprotocol.c:2399
#5  0x0000000000762606 in php_mysqlnd_conn_data_simple_command_send_request_pub (conn=0x7fffd80e0428, command=<optimized out>, arg=0x0, arg_len=0, 
    silent=<optimized out>, ignore_upsert_status=<optimized out>) at /home/chopin/NetBeansProjects/php-src/ext/mysqlnd/mysqlnd.c:341
#6  0x000000000075ff9e in php_mysqlnd_conn_data_simple_command_pub (conn=0x7fffd80e0428, command=COM_QUIT, arg=<optimized out>, arg_len=<optimized out>, 
    ok_packet=PROT_LAST, silent=1 '\001', ignore_upsert_status=1 '\001') at /home/chopin/NetBeansProjects/php-src/ext/mysqlnd/mysqlnd.c:380
#7  0x000000000076176a in php_mysqlnd_conn_data_send_close_pub (conn=0x7fffd80e0428) at /home/chopin/NetBeansProjects/php-src/ext/mysqlnd/mysqlnd.c:1920
#8  0x00000000007622f0 in php_mysqlnd_conn_close_pub (conn_handle=0x7fffd80e03d8, close_type=<optimized out>)
    at /home/chopin/NetBeansProjects/php-src/ext/mysqlnd/mysqlnd.c:3138
#9  0x00000000007f2d9f in zend_ptr_stack_apply (stack=stack@entry=0x7fffd80e03a0, func=func@entry=0x62fdc0 <php_mysqli_dtor_p_elements>)
    at /home/chopin/NetBeansProjects/php-src/Zend/zend_ptr_stack.c:89
#10 0x00000000007f2dbe in zend_ptr_stack_clean (stack=stack@entry=0x7fffd80e03a0, func=func@entry=0x62fdc0 <php_mysqli_dtor_p_elements>, 
    free_elements=free_elements@entry=0 '\000') at /home/chopin/NetBeansProjects/php-src/Zend/zend_ptr_stack.c:96
#11 0x000000000062fedb in php_mysqli_dtor (res=<optimized out>) at /home/chopin/NetBeansProjects/php-src/ext/mysqli/mysqli.c:100
#12 0x0000000000809d9e in plist_entry_destructor (zv=<optimized out>) at /home/chopin/NetBeansProjects/php-src/Zend/zend_list.c:202
#13 0x000000000080724a in _zend_hash_del_el_ex (prev=<optimized out>, p=<optimized out>, idx=<optimized out>, ht=<optimized out>)
    at /home/chopin/NetBeansProjects/php-src/Zend/zend_hash.c:992
#14 _zend_hash_del_el (p=0x7fffd80e01a0, idx=0, ht=0x7fffd805fb10) at /home/chopin/NetBeansProjects/php-src/Zend/zend_hash.c:1016
#15 zend_hash_graceful_reverse_destroy (ht=ht@entry=0x7fffd805fb10) at /home/chopin/NetBeansProjects/php-src/Zend/zend_hash.c:1468
#16 0x000000000080a295 in zend_destroy_rsrc_list (ht=ht@entry=0x7fffd805fb10) at /home/chopin/NetBeansProjects/php-src/Zend/zend_list.c:244
#17 0x00000000007f3995 in executor_globals_dtor (executor_globals=0x7fffd805f8c0) at /home/chopin/NetBeansProjects/php-src/Zend/zend.c:574
#18 0x0000000000787152 in ts_free_thread () at /home/chopin/NetBeansProjects/php-src/TSRM/TSRM.c:465
#19 0x00007ffff0d0b448 in pthreads_prepared_shutdown (thread=thread@entry=0x7ffff78823c0) at /tmp/pear/temp/pthreads/src/prepare.c:709
#20 0x00007ffff0d0fe53 in pthreads_routine (routine=<optimized out>) at /tmp/pear/temp/pthreads/src/object.c:507
#21 0x000000374b807555 in start_thread () from /usr/lib64/libpthread.so.0
#22 0x000000374b502b9d in clone () from /usr/lib64/libc.so.6
```

**Comment by krakjoe** [comment]
I need reproducing code.

**Comment by chopins** [comment]
The below code crash  when mysqli use persistent connect

```php
function db()
{
    //the mysql persistent connect
    $link = new mysqli('p:127.0.0.1', 'root', null);
    return $link;
}
for($i=0;$i<1000;$i++) {
    var_dump(db()->query('SHOW PROCESSLIST')->fetch_all());
}
class myThread extends Thread {
    public function run() {
        db()->query('SHOW PROCESSLIST');
    }
}
for($i=0;$i<10000;$i++) {
    $threads = [
        new myThread(),
        new myThread(),
        new myThread()
    ];
    foreach ($threads as $thread)
        $thread->start();
    foreach ($threads as $thread)
        $thread->join();
}
```

**Comment by krakjoe** [comment]
Can't support persistent resources, the internals for that are so unprepared ... it would be dangerous if it did work ... don't do it ...
