### ISSUE TITLE
[2.0.10] Random segmentation faults on manual garbage collect

### ISSUE THREAD

**Issue by deeky666** [krakjoe/pthreads#558]
I'm trying to build a more advanced threading framework using concepts like futures/promises, channels, executors, executor services etc. This is working out quite well so far except for one key concept `FutureTask`. Those represent the actual work, put onto a synchronized channel and retrieved/executed/resolved by worker threads. The issue occurs while garbage collecting "done" `FutureTask` objects. I'm retrieving random segmentation faults, that do not occur when omitting garbage collecting.

I tried to create a hardly simplified example that reproduces the issue.

```php
<?php

class FutureTask
{
    private $number; // for debug output
    private $monitor;
    private $result;
    
    public function __construct($number)
    {
        $this->number = $number;
        $this->monitor = new \Threaded();
        $this->result = new \Threaded();
        $this->result['done'] = false;
        $this->result['result'] = null;
    }
    
    public function getNumber()
    {
        return $this->number;
    }
    
    public function getResult()
    {
        return $this->monitor->synchronized(
            function () {
                while (!$this->result['done']) {
                    $this->monitor->wait();
                }
                
                return $this->result['result'];
            }
        );
    }
    
    public function isDone()
    {
        if (!$this->result['done']) {
            return false;
        }
        
        // try preventing race conditions
        return $this->monitor->synchronized(
            function () {
                return $this->result['done'];
            }
        );
    }
    
    public function run()
    {
        $this->monitor->synchronized(
            function () {
                var_dump('EXECUTE ' . $this->number);
                usleep(rand(1000, 10000)); // dummy computation
                
                $this->result['result'] = 'foo';
                $this->result['done'] = true;
                var_dump('NOTIFY ' . $this->number);
                $this->monitor->notify();
                var_dump('NOTIFIED ' . $this->number);
                var_dump('EXECUTED ' . $this->number);
            }
        );
    }
}

class WorkerThread extends \Thread
{
    private $channel;
    
    public function __construct($channel)
    {
        $this->channel = $channel;
    }
    
    public function run()
    {
        while (true) {
            $task = $this->channel->synchronized(
                function () {
                     while ($this->channel->count() === 0) {
                         $this->channel->wait();
                     }
                     
                     $task = $this->channel->shift();
                     
                     $this->channel->notify();
                     
                     return $task;
                }
            );
            
            var_dump('RUN ' . $task->getNumber());
            $task->run();
            var_dump('FINISHED ' . $task->getNumber());
        }
    }
}

$taskNumber = 0;
$tasks = array();
$channel = new \Threaded();
$worker = new WorkerThread($channel);

$worker->start();

while (true) {
    $task = new FutureTask($taskNumber);
    $tasks[] = $task;
    
    $channel->synchronized(
        function ($channel) use ($task) {
            $channel[] = $task;
            
            $channel->notify();
        },
        $channel
    );
    
    foreach ($tasks as $index => $task) {
        if ($task->isDone()) {
            var_dump('COLLECT ' . $task->getNumber());
            unset($tasks[$index]);
        }
    }
    
    $taskNumber++;
}
```
The random segfaults I am facing with this example are:
```
string(7) "RUN 199"
string(11) "EXECUTE 199"
string(10) "NOTIFY 199"
string(12) "NOTIFIED 199"
string(12) "EXECUTED 199"
string(12) "FINISHED 199"
string(7) "RUN 200"
string(11) "EXECUTE 200"
string(11) "COLLECT 199"
string(10) "NOTIFY 200"

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb58d1b70 (LWP 22792)]
0x083bd565 in zend_hash_find (ht=0x8d43850, arKey=0xb50aacfc "notify", nKeyLength=6, pData=0xb58d07cc) at /usr/src/builddir/Zend/zend_hash.c:849
849	/usr/src/builddir/Zend/zend_hash.c: No such file or directory.
(gdb) bt
#0  0x083bd565 in zend_hash_find (ht=0x8d43850, arKey=0xb50aacfc "notify", nKeyLength=6, pData=0xb58d07cc) at /usr/src/builddir/Zend/zend_hash.c:849
#1  0xb593c8ce in pthreads_modifiers_get () from /usr/lib/php5/20131226-zts/pthreads.so
#2  0xb593d663 in pthreads_get_method () from /usr/lib/php5/20131226-zts/pthreads.so
#3  0x083ff6b2 in ZEND_INIT_METHOD_CALL_SPEC_VAR_CONST_HANDLER (execute_data=0xb5092514, tsrm_ls=0x8c492f0) at /usr/src/builddir/Zend/zend_vm_execute.h:15747
#4  0x08425cc9 in execute_ex (execute_data=execute_data@entry=0xb5092514, tsrm_ls=tsrm_ls@entry=0x8c492f0) at /usr/src/builddir/Zend/zend_vm_execute.h:363
#5  0x08399511 in dtrace_execute_ex (execute_data=execute_data@entry=0xb5092514, tsrm_ls=0x8c492f0) at /usr/src/builddir/Zend/zend_dtrace.c:73
#6  0x084698ed in zend_execute (op_array=0xb50af9c0, tsrm_ls=tsrm_ls@entry=0x8c492f0) at /usr/src/builddir/Zend/zend_vm_execute.h:388
#7  0x0839bc70 in zend_call_function (fci=0xb50ad35c, fci_cache=0xb50ad1b8, tsrm_ls=0x8c492f0) at /usr/src/builddir/Zend/zend_execute_API.c:829
#8  0xb593986d in pthreads_synchro_block () from /usr/lib/php5/20131226-zts/pthreads.so
#9  0xb5933d00 in zim_Threaded_synchronized () from /usr/lib/php5/20131226-zts/pthreads.so
#10 0x084674f6 in execute_internal (execute_data_ptr=execute_data_ptr@entry=0xb5092340, fci=fci@entry=0x0, return_value_used=return_value_used@entry=0, 
    tsrm_ls=tsrm_ls@entry=0x8c492f0) at /usr/src/builddir/Zend/zend_execute.c:1527
#11 0x0839968a in dtrace_execute_internal (execute_data_ptr=0xb5092340, fci=0x0, return_value_used=0, tsrm_ls=0x8c492f0) at /usr/src/builddir/Zend/zend_dtrace.c:97
#12 0x0846a212 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>, tsrm_ls=<optimized out>) at /usr/src/builddir/Zend/zend_vm_execute.h:560
#13 0x08425cc9 in execute_ex (execute_data=execute_data@entry=0xb5092340, tsrm_ls=tsrm_ls@entry=0x8c492f0) at /usr/src/builddir/Zend/zend_vm_execute.h:363
#14 0x08399511 in dtrace_execute_ex (execute_data=execute_data@entry=0xb5092340, tsrm_ls=0x8c492f0) at /usr/src/builddir/Zend/zend_dtrace.c:73
#15 0x084698ed in zend_execute (op_array=op_array@entry=0xb50aca78, tsrm_ls=tsrm_ls@entry=0x8c492f0) at /usr/src/builddir/Zend/zend_vm_execute.h:388
#16 0x0846ab62 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>, tsrm_ls=0x8c492f0) at /usr/src/builddir/Zend/zend_vm_execute.h:592
#17 0x08425cc9 in execute_ex (execute_data=execute_data@entry=0xb50922a0, tsrm_ls=tsrm_ls@entry=0x8c492f0) at /usr/src/builddir/Zend/zend_vm_execute.h:363
#18 0x08399511 in dtrace_execute_ex (execute_data=execute_data@entry=0xb50922a0, tsrm_ls=0x8c492f0) at /usr/src/builddir/Zend/zend_dtrace.c:73
#19 0x084698ed in zend_execute (op_array=0xb50ad79c, tsrm_ls=0x8c492f0) at /usr/src/builddir/Zend/zend_vm_execute.h:388
#20 0xb593f305 in ?? () from /usr/lib/php5/20131226-zts/pthreads.so
#21 0xb7808c39 in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#22 0xb7775c6e in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
```
In my app the `FutureTask` is a little more advanced but faces similar segfaults. In my case:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb42feb70 (LWP 24313)]
0xb780b1bd in pthread_mutex_lock () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
(gdb) bt
#0  0xb780b1bd in pthread_mutex_lock () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#1  0xb7782f26 in pthread_mutex_lock () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#2  0xb59396cd in pthreads_synchro_lock () from /usr/lib/php5/20131226-zts/pthreads.so
#3  0xb59397a9 in pthreads_synchro_block () from /usr/lib/php5/20131226-zts/pthreads.so
#4  0xb5933d00 in zim_Threaded_synchronized () from /usr/lib/php5/20131226-zts/pthreads.so
#5  0x084674f6 in execute_internal (execute_data_ptr=execute_data_ptr@entry=0x95e46f4, fci=fci@entry=0x0, return_value_used=return_value_used@entry=1, 
    tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_execute.c:1527
#6  0x0839968a in dtrace_execute_internal (execute_data_ptr=0x95e46f4, fci=0x0, return_value_used=1, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_dtrace.c:97
#7  0x0846a212 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>, tsrm_ls=<optimized out>) at /usr/src/builddir/Zend/zend_vm_execute.h:560
#8  0x08425cc9 in execute_ex (execute_data=execute_data@entry=0x95e46f4, tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:363
#9  0x08399511 in dtrace_execute_ex (execute_data=execute_data@entry=0x95e46f4, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_dtrace.c:73
#10 0x084698ed in zend_execute (op_array=op_array@entry=0x9771864, tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:388
#11 0x0846ab62 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:592
#12 0x08425cc9 in execute_ex (execute_data=execute_data@entry=0x95e465c, tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:363
#13 0x08399511 in dtrace_execute_ex (execute_data=execute_data@entry=0x95e465c, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_dtrace.c:73
#14 0x084698ed in zend_execute (op_array=op_array@entry=0x977028c, tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:388
#15 0x0846ab62 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:592
#16 0x08425cc9 in execute_ex (execute_data=execute_data@entry=0x95e45cc, tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:363
#17 0x08399511 in dtrace_execute_ex (execute_data=execute_data@entry=0x95e45cc, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_dtrace.c:73
#18 0x084698ed in zend_execute (op_array=op_array@entry=0x976fb8c, tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:388
#19 0x0846ab62 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:592
#20 0x08425cc9 in execute_ex (execute_data=execute_data@entry=0x95e4520, tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:363
#21 0x08399511 in dtrace_execute_ex (execute_data=execute_data@entry=0x95e4520, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_dtrace.c:73
#22 0x084698ed in zend_execute (op_array=op_array@entry=0x9764bac, tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:388
#23 0x0846ab62 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:592
#24 0x08425cc9 in execute_ex (execute_data=execute_data@entry=0x95e43d4, tsrm_ls=tsrm_ls@entry=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:363
#25 0x08399511 in dtrace_execute_ex (execute_data=execute_data@entry=0x95e43d4, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_dtrace.c:73
#26 0x084698ed in zend_execute (op_array=0x95fe240, tsrm_ls=0x95e0278) at /usr/src/builddir/Zend/zend_vm_execute.h:388
#27 0xb593f305 in ?? () from /usr/lib/php5/20131226-zts/pthreads.so
#28 0xb7808c39 in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#29 0xb7775c6e in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
```
This segfault is encountered as soon as calling `synchronized()` on the monitor object in `FutureTask` derivation in my app.

I might be doing somehting wrong, so clarifications about how to do it "the right way" are welcome. Otherwise using pthreads 3 is not an option yet and sticking to the builtin `Worker` and `Pool` classes isn't either so I would be very pleased if you could consider my situation.

I am using PHP 5.6.17 on Debian Wheezy.

Thanks for your help!

**Comment by krakjoe** [comment]
Sorry, but I just don't have time to support v2 any more :(

Please upgrade to v3.
