### ISSUE TITLE
Out of resources on php 7.0.2 x86 + pthreads 3.1.5

### ISSUE THREAD

**Issue by astro-train** [krakjoe/pthreads#559]
Here's the simpliest code to reproduce the issue 
```
<?php 
class WorkerThreads extends Thread
{
    private $workerId;
    private $url;

    public function __construct($string)
    {
        $this->url = $string;
    }

    public function run()
    {

        $curl = curl_init();

        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_URL, $this->url);

        if ($this->post) {
            curl_setopt($curl, CURLOPT_POSTFIELDS, $this->post);
        }

        $response = curl_exec($curl);
        //echo $response;
        curl_close($curl);
    }
}

$data = file('urls.txt'); 
$data_size = count($data);
// Worker pool
$workers = [];
$t_count = 100;
$flag = 1;
$k = 0;

while($flag === 1)
{   

    $c_w = count($workers);

    if($c_w < $t_count)
    {
        for($i = $c_w; $i<$t_count - $c_w;$i++)
        {
            if($k >= $data_size)
            {
                $flag = 0;
                break;
            }   

            $url = explode("|",$data[$k]);
            $workers[$i] = new WorkerThreads($url[0]);
            echo $k." ".$url[0]."\n";
            $workers[$i]->start();
            $k++;   
        }

    }

    $c_w = count($workers);
    for($i=0;$i<$c_w;$i++)
    {
        if($workers[$i]->join())
        {
            //echo "joining $i\n";
            unset($workers[$i]);

        }
    }


}

?>


```

It gives exception:

```

PHP Fatal error:  Uncaught RuntimeException: cannot start WorkerThreads, out of
resources in C:\Users\alex\Desktop\test.php:56
Stack trace:
#0 C:\Users\alex\Desktop\test.php(56): Thread->start()
#1 {main}
  thrown in C:\Users\alex\Desktop\test.php on line 56

Fatal error: Uncaught RuntimeException: cannot start WorkerThreads, out of resou
rces in C:\Users\alex\Desktop\test.php:56
Stack trace:
#0 C:\Users\alex\Desktop\test.php(56): Thread->start()
#1 {main}
  thrown in C:\Users\alex\Desktop\test.php on line 56
```

However, on x64 version everything works. The ini settings is default, except for adding pthreads extension and increasing memory to 3GB.

**Comment by krakjoe** [comment]
There is a hard limit on the number of threads your system can create, pthreads cannot change it: Start less threads.

**Comment by hutnikau** [comment]
I have the same issue after I update php to version 7.0.10 (and pthreads to 3.1.6). But on php 5.6 it worked without any issues.
