### ISSUE TITLE
MongoDB and pthreads

### ISSUE THREAD

**Issue by skoteg** [krakjoe/pthreads#851]
Joe, good afternoon.

Is it possible to multi-thread mongodb driver and iterators?
Now when you try to execute the following code:

```php
<?php>
// one provider for several threads
class dataProvider extends Threaded
{
	private $db = null;
	private $cur = null;
	private $it = null;

	public function __construct()
	{
		$this->db = new MongoDB\Driver\Manager(
			'mongodb://127.0.0.1/',
			['connectTimeoutMS' => 120000]
		);
		$opts = [
			'projection' => [],
			'sort' => [],
			'limit' => false,
			'skip' => 0,
			'modifiers' => ['$maxTimeMS' => 120000],
		];
		$query = new MongoDB\Driver\Query([], $opts);
		$this->cur = $this->db->executeQuery('resolute.documents', $query);
		$this->cur->setTypeMap(['root' => 'array', 'document' => 'array', 'array' => 'array']);
		$this->it = new IteratorIterator($this->$cur);
		$this->it->rewind();
	}
	public function getNext()
	{
		return $this->it->next();
	}
}

$provider = new dataProvider();
```
error occurs:
```
[resolute@localhost os]$ /srv/resolute7/bin/php ./mt_test_1.php

Fatal error: Uncaught Error: Call to a member function executeQuery() on null in /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php:24
Stack trace:
#0 /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php(84): dataProvider->__construct()
#1 {main}
  thrown in /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php on line 24
[resolute@localhost os]$
```
If the variables $db, $cur, $it make static:
```php
<?php>
// one provider for several threads
class dataProvider extends Threaded
{
	private static $db = null;
	private static $cur = null;
	private static $it = null;

	public function __construct()
	{
		self::$db = new MongoDB\Driver\Manager(
			'mongodb://resolute:qWoGvSmL@%2Fsrv%2Fresolute7%2Frun%2Fmongodb-27017.sock/resolute_vtb',
			['connectTimeoutMS' => 120000]
		);
		$opts = [
			'projection' => [],
			'sort' => [],
			'limit' => false,
			'skip' => 0,
			'modifiers' => ['$maxTimeMS' => 120000],
		];
		$query = new MongoDB\Driver\Query([], $opts);
		self::$cur = self::$db->executeQuery('resolute_vtb.documents', $query);
		self::$cur->setTypeMap(['root' => 'array', 'document' => 'array', 'array' => 'array']);
		self::$it = new IteratorIterator(self::$cur);
		self::$it->rewind();
	}
	public function getNext()
	{
		return self::$it->next();
	}
}

class _worker extends Worker
{
	private $provider;

	public function __construct(dataProvider $provider)
	{
		$this->provider = $provider;
	}
	public function getProvider()
	{
		return $this->provider;
	}
	public function run() {}
}

class _thread extends Threaded
{
	private $num;
	public function __construct($num)
	{
		$this->num = $num;
	}

	public function run()
	{
		do {
			$value = null;
			$provider = $this->worker->getProvider();

			// Synchronize getting data from dataProvider
			$provider->synchronized(
				function($provider) use (&$value) {
					$value = $provider->getNext();
				},
				$provider
			);
			if ($value === null) {
				continue;
			}

			// useful action. For example save to file
			// $this->num - is number of thread
			file_put_contents($this->num, $value['code']);
		}
		while ($value !== null);
	}
}

$thrCnt = 4;
$provider = new dataProvider();
$pool = new Pool($thrCnt, '_worker', [$provider]);
for ($i = 0; $i < $thrCnt; $i++) {
	$pool->submit(new _thread($i));
}
$pool->shutdown();
```
error occurs:
```
[resolute@localhost os]$ /srv/resolute7/bin/php ./mt_test_1.php

Fatal error: Uncaught Error: Call to a member function next() on null in /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php:31
Stack trace:
#0 /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php(67): dataProvider->getNext()
#1 [internal function]: _thread->{closure}(Object(dataProvider))
#2 /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php(69): Threaded->synchronized(Object(Closure), Object(dataProvider))
#3 [internal function]: _thread->run()
#4 {main}
  thrown in /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php on line 31

**Comment by robske110** [comment]
Please always note that static properties are always thread-local, even on Threaded objects.

**Comment by skoteg** [comment]
But when variables are declared as class variables, then an error occurs:
```
Fatal error: Uncaught Error: Call to a member function executeQuery() on null
```
in string
```php
$this->cur = $this->db->executeQuery('resolute.documents', $query);
```
in code:
```php
class dataProvider extends Threaded
{
	private $db = null;
	private $cur = null;
	private $it = null;

	public function __construct()
	{
		$this->db = new MongoDB\Driver\Manager(
			''mongodb://127.0.0.1/',
			['connectTimeoutMS' => 120000]
		);
		$opts = [
			'projection' => [],
			'sort' => [],
			'limit' => false,
			'skip' => 0,
			'modifiers' => ['$maxTimeMS' => 120000],
		];
		$query = new MongoDB\Driver\Query([], $opts);
		$this->cur = $this->db->executeQuery('resolute.documents', $query);
		$this->cur->setTypeMap(['root' => 'array', 'document' => 'array', 'array' => 'array']);
		$this->it = new IteratorIterator($this->$cur);
		$this->it->rewind();
	}
	public function getNext()
	{
		return $this->it->next();
	}
}
```

**Comment by skoteg** [comment]
Yes, probably the problem is that MongoDB \ Driver \ Manager does not support serialization.
That is, Mondogb can not work with ptkhreads?

**Comment by tpunt** [comment]
The fundamental problem here is that you are trying to reuse the *same* MongoDB connection between threads.

As you have observed, attempting to assign a resource to an instance property will cause `null` to be assigned instead, since certain objects (such as those tied to resources, like a DB connection), are not serialisable. You are able to assign such objects (and resources) to static properties because they are thread-local, and so they're not serialised. Because they are thread-local, however, they are not accessible by other threads.

The solution to your problem is to use one database connection per thread.
